- README.md
- ph-ee-connector-ams-mifos
- ph-ee-connector-channel
- ph-ee-connector-mojaloop-java 
- ph-ee-importer-rdbms
- ph-ee-operations-app
> added docker image links for phee

- helm/superset/values.yaml
* Tenants renamed to `gorilla` and `lion` from `ibank-usa` and `ibank-india` respectively.
> Tenants renamed to gorilla & lion in superset

- helm/g2p-sandbox/values.yaml
* Enabled ams-mifos in g2p-sandbox environment.
> Enabled the ams-mifos for g2p-sandbox

- helm/superset/values.yaml
> Pointing ingresses to tls

- helm/superset/values.yaml
* Changed operations image and tag to point to ECR
> Changed image to ECR

- helm/g2p-sandbox/Chart.yaml
- helm/g2p-sandbox/values.yaml
* Protocol updated to http for es and kibana
> Protocol updated to http for es and kibana

- helm/superset/values.yaml
* Enabled mojaloop connector for superset chart.
* Udated mojaloop image reference.
* Fixed [PHEE-180](https://fynarfin.atlassian.net/browse/PHEE-180?atlOrigin=eyJpIjoiYjhhZGNkMWI0NzNhNDdkNWFmYTA0Nzc1MjJiNTgxOTAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[PHEE-180]: https://fynarfin.atlassian.net/browse/PHEE-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixes PHEE-180 : Enabled mojaloop and fixed PHEE-180

- helm/superset/values.yaml
Adding variables to handle ES security
> Adding variables to handle ES security

- helm/superset/values.yaml
* Addresses below tickets
[PHEE-180](https://fynarfin.atlassian.net/browse/PHEE-180)
[PHEE-183](https://fynarfin.atlassian.net/browse/PHEE-183)
[PHEE-180]: https://fynarfin.atlassian.net/browse/PHEE-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PHEE-183]: https://fynarfin.atlassian.net/browse/PHEE-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Mojaloop ingress enabled

- helm/superset/values.yaml
* Updated tenants host from mifos.g2pconnect.io to fynarfin.io
> update tenants hosts

- helm/g2p-sandbox/values.yaml
> mojaloop-ingress-changes

- helm/superset/values.yaml
> [FIX] Updated keycloak secret env variable

- helm/superset/values.yaml
> Added Kong variables in env from template

- helm/superset/values.yaml
> Make config for ops web to be empty

- helm/g2p-sandbox/Chart.yaml
- helm/superset-release/Chart.yaml
- helm/superset-release/templates/config.yml
- helm/superset-release/values.yaml
* Created the ph-ee-superset-release chart
> create superset-release and name superset chart

- helm/superset/values.yaml
> Added loan host

- helm/superset/values.yaml
Kibana not coming in kibana due to improperly set ES host 
> Editing es hosts value to fix kibana startup issue

- helm/superset-release/templates/config.yml
* Ph-ee-config is existed in ph-ee-engine, deleted from superset-release chart
> deleted ph-ee-config

- helm/superset-release/Chart.yaml
- helm/superset-release/values.yaml
> added version tag to image

- helm/superset/values.yaml
To address multiple issues related to override application.yml values
Related PRs: 
https://github.com/openMF/ph-ee-connector-channel/pull/60
https://github.com/openMF/ph-ee-env-template/pull/88
@fynmanoj 
@somanath21 
> Adding new values for various zeebe vars for channel

- helm/superset-release/values.yaml
- helm/superset/Chart.yaml
> release-1.5.2

- helm/superset-release/values.yaml
* bulk-processor-release-added
> bulk-processor-release

- helm/superset/values.yaml
> Updated the AMS local enabled config

- .gitignore
- orchestration/feel/example/PayeePartyLookup-gorilla.bpmn
- orchestration/feel/example/PayeePartyLookup-rhino.bpmn
- orchestration/feel/example/PayeeQuoteTransfer-gorilla.bpmn
- orchestration/feel/example/PayeeQuoteTransfer-rhino.bpmn
- orchestration/feel/example/PayerFundTransfer-gorilla.bpmn
- orchestration/feel/example/PayerFundTransfer-rhino.bpmn
- orchestration/feel/example/gsma_base_transaction-gorilla.bpmn
- orchestration/feel/example/gsma_base_transaction-rhino.bpmn
- orchestration/feel/example/international_remittance_payee_process-gorilla.bpmn
- orchestration/feel/example/international_remittance_payee_process-rhino.bpmn
* Added example bpmn for gorilla and rhino dfsp. Only for gsma p2p and mojaloop fund transfer.
[PHEE-239](https://fynarfin.atlassian.net/browse/PHEE-239)
[PHEE-239]: https://fynarfin.atlassian.net/browse/PHEE-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed PHEE-239 Added example for rhino and gorilla tenant gsma and mojaloop bpmn

- helm/superset/config/application-fin12.properties
* Added fspid for gorilla: payerfsp and rhino: payeefsp
> FSPID updated in superset for mojaloop

- helm/superset/values.yaml
- Added new variables for reporting index
> Added new variables

- helm/superset-release/values.yaml
- helm/superset/Chart.yaml
> Updated version

- helm/superset/values.yaml
- Removed indent in reporting variable
> Removed indent in reporting variable

- helm/superset-release/values.yaml
> Updated superset release values.yaml

- helm/superset/values.yaml
> Added Redis

- helm/superset/Chart.yaml
> Updated Chart.yaml

- helm/superset/Chart.yaml
- helm/superset/values.yaml
* Updated the Chart version of ph-ee-engine to v1.7.2
> chart version update

- helm/superset/Chart.yaml
> fixed chart repo

- helm/operations/Chart.yaml
- helm/operations/values.yaml
- helm/ph-ee-fin-front-end/values.yaml
* Removed unnecessary backend services.
* It contains only 4 services:
1. mifos-community
2. kibana
3. ph-ee-operations-web
4. grafana
> fix for front end helm chart

- helm/ph-ee-fin-back-end/values.yaml
* Removed front-end services.
* Changed ingresses to mifos.io
> fix for backend chart

- helm/ES-security/Makefile
- helm/ES-security/examples.mk
- helm/kibana-secret/example.mk
- helm/kibana-secret/examples.mk
- helm/kibana-secret/makefile
* Created a Folder for ES Security to create ES-secrets using makefile and example.mk file 
* mention namespace in a makefile to create ES secrets in specific namespaces.
> Created makefile and example.mk for ES secrets

- helm/g2p-sandbox/config/application-tenants.properties
- helm/g2p-sandbox/values.yaml
Adding tenants yml and adding same in channel values for tenant to use case to implementation ([GOV-338)](https://mifosforge.jira.com/browse/GOV-338)
> Tenant to use case to implementation (GOV 338)

- orchestration/feel/minimal_mock_fund_transfer-DFSPID.bpmn
Modified https://github.com/openMF/ph-ee-env-labs/pull/112 to correct a missing a condition
> Fund tranfer bpmn with payee only

- helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
- helm/g2p-sandbox-fynarfin-SIT/values.yaml
* Added Ingress hostname to fynarfin specific
> added Ingress hostname to fynarfin specific

- helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
- helm/g2p-sandbox-fynarfin-SIT/values.yaml
* Disabled kong and added Annotations for Bulk and ops_web to disable kong 
> G2psandbox chart

- helm/ph-ee-fin-back-end/values.yaml
* Adding env spec for fineract in back-end chart
* Disabling keycloak, gsma, and mojaloop service in back-end chart.
> Adding env spec for fineract

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[Updated tenant PHEE-327](https://fynarfin.atlassian.net/browse/PHEE-327)
> PHEE-327 Updated tenant value name 

- helm/g2p-sandbox-fynarfin-SIT/config/application-bb.properties
- helm/g2p-sandbox-fynarfin-SIT/config/application-fin12.properties
- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[##](https://mifosforge.jira.com/jira/software/c/projects/GOV/issues/GOV-525?filter=allissues) Description
* Updated mojaloop imageTag
* Enabled kibana ingress
* Updated zeebe Broker contactpoint 
> GOV-525 enabled kibana ingress ML image tag and update Zeebe BCP

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
- [PHEE-359 Wrong operations app contactpoint in channel pod](https://fynarfin.atlassian.net/browse/PHEE-359?atlOrigin=eyJpIjoiODM0ZWE0ZGYyOGZjNGQ4MDgwNjllN2ZlZTExNmRiYmUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-359 Wrong operations app contactpoint in channel

- .circleci/config.yml
- orchestration/deployBpmn.sh
(https://mifosforge.jira.com/browse/GOV-528) Description
* Added bpmn-upload pipeline to CircleCI to test in CircleCI
> #GOV-528 Upload BPMN in CircleCI 

- helm/ph-ee-fin-back-end/Chart.yaml
- helm/ph-ee-fin-back-end/values.yaml
[PHEE-364 Remove duplicates from the ph-ee-fin-back-end values.yaml](https://fynarfin.atlassian.net/browse/PHEE-364?atlOrigin=eyJpIjoiZTdhNDMwM2UxOTg3NDQ4NmFjNTNmYTJhNGE4YWVlMDEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-364 Remove duplicates from the ph-ee-fin-back-end values.yaml

- .circleci/config.yml
- [PHEE-363 Add gradlew test for @AMSIntegration suite](https://fynarfin.atlassian.net/browse/PHEE-363?atlOrigin=eyJpIjoiNDg5MzdjYTIxYjA1NGRiYjhlNzY0MjE0MTQ5NDJhMjQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-363 Added gradlew test for @AMSIntegration suite

- helm/ph-ee-fin-back-end/Makefile
- helm/ph-ee-fin-back-end/examples.mk
- helm/ph-ee-fin-back-end/kong-keycloak-realm.json
- helm/ph-ee-fin-back-end/templates/relm-secret.yaml
[PHEE-324 Create a makefile to deploy secrets for back-end chart](https://fynarfin.atlassian.net/browse/PHEE-324?atlOrigin=eyJpIjoiZWUzZWRkNWQxYmE0NGE5NDlhNjkwZDUxYTRiOGI3MmYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
* Fix for all secrets issues
* Makefile to install all the secrets.
> PHEE-324 Create a makefile to deploy secrets for back-end chart

- helm/ph-ee-fin-front-end/values.yaml
[PHEE-325 Fix for auth.token is nil issue in front-end chart](https://fynarfin.atlassian.net/browse/PHEE-325?atlOrigin=eyJpIjoiOWM4MDcyODA5N2MwNDE1NjhmZjk0NzQ1ZDllYzgyN2IiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
* Fix for Secret.data.auth-token is nil issue while doing helm upgrade.
> PHEE-325 Fix for auth.token is nil issue in front-end chart

- .circleci/config.yml
- helm/g2p-sandbox-fynarfin-SIT/values.yaml
- [PHEE-366 Update region and parameterize in contexts](https://fynarfin.atlassian.net/browse/PHEE-366?atlOrigin=eyJpIjoiMDNkN2ViOWJmNzFhNDlhZjg1NjE1ZmVmODU3ZTY0MmUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-366 Updated region and parameterized

- helm/ph-ee-fin-front-end/values.yaml
[PHEE-365 Remove duplicates from ph-ee-fin-front-end values.yaml](https://fynarfin.atlassian.net/browse/PHEE-365?atlOrigin=eyJpIjoiMTZmMjMwZDhjMWMzNGNhZmIxY2I3YmE2Y2EwNTQzZTIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-365 Remove duplicates from ph-ee-fin-front-end values.yaml

- .circleci/config.yml
[PHEE-379 Update the bulk-processor-secret with circleci variables.](https://fynarfin.atlassian.net/browse/PHEE-379?atlOrigin=eyJpIjoiNTNjNTcyMDk2MDU0NDcxY2IyYTk2YWE4NTU5ZmM1ZGIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-379 Update the bulk-processor-secret with circleci variables.

- helm/g2p-sandbox-fynarfin-SIT/config/application-tenants.properties
Fixes the error for minimal mock fund transfer TC
> Fix for minimal mock fund transfer TC

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[PHEE-381 fix kibana ingress issue](https://fynarfin.atlassian.net/browse/PHEE-381?atlOrigin=eyJpIjoiZTIxODMyODc2NGRiNGQwZjk2ZWU5MWU5N2RiYTgzNWUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-381 fix kibana ingress issue

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
This PR would add ingress for Mock Payment Schema.
Jira link: [GOV-301](https://mifosforge.jira.com/browse/GOV-301)
[GOV-301]: https://mifosforge.jira.com/browse/GOV-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-301: Add ingress for mock payment schema

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
Update ingress for Mock Payment Schema.
> PHEE-104: Update mock payment schema ingress

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
> Identity Account Mapper

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
* Adding rollme annotations for account mapper.
> GOV-517 Identity Account Mapper deployment annotation

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
Jira link: [GOV-301](https://mifosforge.jira.com/browse/GOV-301)
[GOV-301]: https://mifosforge.jira.com/browse/GOV-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-301: Add load balancer for mock payment schema

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
* Adding vouchers in fynarfin SIT chart.
> Adding vouchers in fynarfin SIT

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[GOV-287](https://mifosforge.jira.com/browse/GOV-287)
[GOV-287]: https://mifosforge.jira.com/browse/GOV-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV 287: Bulk ingress migrated to kong

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
> config-change-work-around-for-fineract-url

- helm/g2p-sandbox-fynarfin-SIT/config/application-tenants.properties
[PHEE-409 Modify tenant-flow config in env-labs](https://fynarfin.atlassian.net/browse/PHEE-409?atlOrigin=eyJpIjoiMDNlY2IxYTM1NmZhNDRiZTg0ODE2MzVkNDk5YjU5MjUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[PHEE-422 Create minimalMockTransferRequest BPMN, its workers, required configurations, integration test](https://fynarfin.atlassian.net/browse/PHEE-422?atlOrigin=eyJpIjoiOGZlZTE1MTBjOGVmNDhjMTg3ODEyMWI5MjU2M2NiNDAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-409 tenant configuration update (+PHEE-422)

- helm/g2p-sandbox-fynarfin-SIT/config/application-tenants.properties
[PHEE-428 update tenant-bpmn mapping for payment transfer usecase](https://fynarfin.atlassian.net/browse/PHEE-428?atlOrigin=eyJpIjoiNGVhNzQ2MjNjOGNjNDc0M2FlMDQ1NmMwMTQzM2RiNmIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-428 update tenant-bpmn mapping for payment transfer usecase

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[PHEE-442 Configure ams_local_loan_host flag in ams_mifos](https://fynarfin.atlassian.net/browse/PHEE-442?atlOrigin=eyJpIjoiMWNhNjg4MTQ3NGQ0NDkyN2FiYTk4OTgzOTc1ODAwZjQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-442 Configure ams_local_loan_host flag in ams_mifos

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[PHEE-444 Create an ingress that points to ams mifos mock server.](https://fynarfin.atlassian.net/browse/PHEE-444?atlOrigin=eyJpIjoiZTUxNDU5MWQ2NjEwNGYzM2FiYzc0ZWNlMDJlNDFhNTUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-444 Create an ingress that points to ams mifos mock server.

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
> GOV-517 Adding IAM hostname

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[PHEE-461 Update mojaloop tls secret in env-labs](https://fynarfin.atlassian.net/browse/PHEE-461?atlOrigin=eyJpIjoiNTE1ZTEwNGI2YTQ0NGJkZjlkNzNjYTRiMjY1ZGZmZWEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
@fynmanoj 
> PHEE-461 Update mojaloop tls secret in env-labs

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
* Migrated channel ingress to kong
[GOV-287](https://mifosforge.jira.com/browse/GOV-287)
Linked PR: https://github.com/openMF/ph-ee-env-template/pull/242
[GOV-287]: https://mifosforge.jira.com/browse/GOV-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-287.3: Migrated channel ingress to kong

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[GOV-287](https://mifosforge.jira.com/browse/GOV-287)
Linked PR: https://github.com/openMF/ph-ee-env-labs/pull/174
[GOV-287]: https://mifosforge.jira.com/browse/GOV-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Gov 287.3 Added Channel service annotation

- .circleci/services.txt
[PHEE-477 Create an orb that fetches the docker images and do helm upgrade](https://fynarfin.atlassian.net/browse/PHEE-477?atlOrigin=eyJpIjoiNDU5MjQzNzc4MGJhNDA1YmFhMmQ0MGI4OGU2ZmEyNDgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-477] Create an orb that fetches the docker images and do helm upgrade

- .circleci/config.yml
- .circleci/services.txt
- .github/pull_request_template.md
[PHEE-490 Publish helm chart with jira ticket from circleci](https://fynarfin.atlassian.net/browse/PHEE-490?atlOrigin=eyJpIjoiMmIxNmNhNzY4MGI5NGZhMGFmNmI0ZDE0ZTVkMWQwZWEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-490] Publish helm chart with jira ticket from circleci

- orchestration/deployBpmn.sh
[PHEE-499 Worker DFSPIDs in inbound-ams-mifo.bpmn workflow is not changing wh…](https://fynarfin.atlassian.net/browse/PHEE-499?atlOrigin=eyJpIjoiMjkyNDU4NjkzZmI0NDc5ODk1OTA5ZjgxYmRlM2RiNGUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-499] Worker DFSPIDs in inbound-ams-mifo.bpmn workflow is not changing while uploading

- .circleci/config.yml
[PHEE-500 Apply check for chart availability during deployment.](https://fynarfin.atlassian.net/browse/PHEE-500?atlOrigin=eyJpIjoiMzZhZGY5NzJjMzlkNDhkYWI5MWYzMzY3MTM2MTE1MWUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-500] Apply check for chart availability during deployment.

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[PHEE-496 Update ml-connector config](https://fynarfin.atlassian.net/browse/PHEE-496?atlOrigin=eyJpIjoiZTIzZTY5ODA2N2Y1NDAyY2JhZDU3YWJjOTkwODkxNjQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-496] Update ml-connector config

- .circleci/services.txt
> [GOV-83] Added services in service txt

- .circleci/services.txt
> [GOV-83] Changing docker image for ph-ee-connector

- .circleci/config.yml
- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[PHEE-494 Add Minio to the ph ee engine helm chart](https://fynarfin.atlassian.net/browse/PHEE-494?atlOrigin=eyJpIjoiZjQ4MjNhZmJmZTdlNDEyZGJhNTAyYzE0MjcyZjkwMWEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-494] Add Minio to the ph ee engine helm chart

- .circleci/config.yml
- helm/g2p-sandbox-fynarfin-SIT/values.yaml
(https://fynarfin.atlassian.net/browse/PHEE-503)
> [PHEE-503] Post installation job 

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[PHEE-551 Get Operations-web up and running](https://fynarfin.atlassian.net/browse/PHEE-551?atlOrigin=eyJpIjoiY2MxMjJiMjdjZDBmNDZlMmE1MGE3NzhlYjYwMmE2MGUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-551] Get Operations-web up and running

- .circleci/services.txt
> [phee-660] Update services.txt with integration-test image

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
> [PHEE-584] Fix the DFSP IDs work around from SIT chart

- orchestration/feel/gsma_base_transaction-DFSPID.bpmn
> [PHEE-588] Fix BPMN for AMS TCs

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[PHEE-594 fix mojaloop testcases](https://fynarfin.atlassian.net/browse/PHEE-594?atlOrigin=eyJpIjoiMjlkMjBiNGY3NmNlNDk2NGJjY2Q0YWU0ZDBjMDJmOWUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-594] fix mojaloop testcases

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[PHEE-648 Fix AWS s3 status code 404 issue.](https://fynarfin.atlassian.net/browse/PHEE-648?atlOrigin=eyJpIjoiYmFjMGZmOTFlZTVhNGI0ZmI1ZmM4OTNmMzkzYzAwMGIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-648] Fix AWS s3 status code 404 issue.

- .circleci/services.txt
> [PHEE-646] Adding zeebe ops in services file

- helm/operations/values.yaml
[PHEE-657 Enable k8s dashboard in grafana](https://fynarfin.atlassian.net/browse/PHEE-657?atlOrigin=eyJpIjoiM2EwYzYzNmM4OGNlNDc2OThjYzU2NjAzZDAyNmY4MTQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-657] Enable k8s dashboard in grafana

- helm/operations/values.yaml
[PHEE-662 Config Prometheus to prevent running out of space](https://fynarfin.atlassian.net/browse/PHEE-662?atlOrigin=eyJpIjoiOTBmZGFkMzkyMDJhNDU1NzlkY2FlMjBkNWIyNzE3MTIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-662] Config Prometheus to prevent running out of space

- helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
- helm/g2p-sandbox-security-fynarfin-SIT/Chart.yaml
> version upgrade 1.6.0

- .circleci/config.yml
- helm/ph-ee-g2p-sandbox-ci/Chart.yaml
- helm/ph-ee-g2p-sandbox-ci/values_p1.yaml
- helm/ph-ee-g2p-sandbox-ci/values_p2.yaml
- helm/ph-ee-g2p-sandbox-ci/values_p3.yaml
- helm/ph-ee-g2p-sandbox-ci/values_resource.yaml
[PHEE-674 Create ph-ee-g2p-sandbox-ci chart](https://fynarfin.atlassian.net/browse/PHEE-674?atlOrigin=eyJpIjoiNzBmMDY1Y2JmMDY2NGFhNzhkNTI0MzkwYzI3Y2I1ZTUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-674] Create ph-ee-g2p-sandbox-ci chart

- helm/g2p-sandbox-extended/Chart.yaml
- helm/g2p-sandbox-extended/README.Md
- helm/g2p-sandbox-extended/templates/test/integration-test-e2e.yaml
- helm/g2p-sandbox-extended/values.yaml
> Chart to install g2p-sandbox, fineract and mojaloop with placeholders

- helm/g2p-sandbox-fynarfin-SIT/values.yaml
[PHEE-699 Parallel Payee-Multi-Tenancy-Support in channel Transfer API](https://fynarfin.atlassian.net/browse/PHEE-699?atlOrigin=eyJpIjoiZmUzYzljYjFlNDE1NDg1MWEwNTJhM2YxZDg1NzgwMWIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-699] Parallel Payee-Multi-Tenancy-Support in channel Transfer API

- helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
- helm/g2p-sandbox-security-fynarfin-SIT/Chart.yaml
> release process v1.6.2
